#! /bin/bash
####### Define Variables ######
echo "What is the domain name?"
read DOMAINNAME

echo "Enter your GoDaddy API Key"
read DOMAINAPIKEY

echo "Enter your GoDaddy API Secret"
read DOMAINAPISECRET

echo "Enter your Google OAuth Client ID"
read OAUTHCLIENT

echo "Enter your Google OAuth Secret"
read OAUTHSECRET

echo "Enter comma separated list of authorized users.  ie. user1@gmail.com,user2@gmail.com,"
read AUTHORIZEDUSERS

echo "Enter Certificate Contact Email Address"
read CERTCONTACT

echo "Enter path for Docker data.  ie. /mnt/docker"
read DOCKERPATH


###############################


##########   Docker ###########
while true; do
    read -p "Install Docker?" yn
    case $yn in
        [Yy]* ) sh ./components/docker.sh ; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

###############################

######### Watchtower #############
echo "Installing Watchtower"
sh ./components/watchtower.sh

###############################

######### Traefik #############

while true; do
    read -p "Install Traefik?" yn
    case $yn in
        [Yy]* ) sh ./components/traefik.sh ; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

###############################

######### oAuth #############

while true; do
    read -p "Install oAuth?" yn
    case $yn in
        [Yy]* ) sh ./components/oauth.sh ; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

###############################


######### Plex #############

while true; do
    read -p "Install Plex?" yn
    case $yn in
        [Yy]* ) sh ./components/plex.sh ; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

###############################

######### NZBGet #############

while true; do
    read -p "Install NZBGet?" yn
    case $yn in
        [Yy]* ) sh ./components/nzbget.sh ; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

###############################

######### Deluge #############

while true; do
    read -p "Install Deluge?" yn
    case $yn in
        [Yy]* ) sh ./components/deluge.sh ; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

###############################

######### Deluge #############

while true; do
    read -p "Install Deluge?" yn
    case $yn in
        [Yy]* ) sh ./components/deluge.sh ; break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

###############################